name: Financial Analysis CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify Python version (adjust as needed)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy matplotlib statsmodels jupyter nbconvert

      # Step 4: Create output directories
      - name: Create output directories
        run: |
          mkdir -p data
          mkdir -p plots

      # Step 5: Run the Jupyter Notebook
      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute financial_analysis.ipynb --output executed_notebook.ipynb
        continue-on-error: false

      # Step 6: Validate output files
      - name: Check output files
        run: |
          # Check if CSV files exist for each ticker
          for ticker in TSLA BND SPY; do
            if [ ! -f "data/${ticker}_data.csv" ]; then
              echo "Error: data/${ticker}_data.csv not found"
              exit 1
            fi
          done
          # Check if plot files exist
          for file in adj_close_prices.png daily_returns.png rolling_volatility.png; do
            if [ ! -f "plots/${file}" ]; then
              echo "Error: plots/${file} not found"
              exit 1
            fi
          done
          # Check if insights file exists
          if [ ! -f "plots/eda_insights.txt" ]; then
            echo "Error: plots/eda_insights.txt not found"
            exit 1
          fi

      # Step 7: Upload artifacts (optional, for debugging)
      - name: Upload output files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: financial-analysis-outputs
          path: |
            data/*.csv
            plots/*.png
            plots/*.txt
          retention-days: 7

      # Step 8: Clean up (optional)
      - name: Clean up
        if: always()
        run: |
          rm -rf data plots executed_notebook.ipynb